apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dreamkast-dk-1178
bases:
- ../../../base
resources:
- ns.yaml
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- viewer-count.yaml
- polling-harvest-job-and-update-video.yaml
- deployment-fifo-worker.yaml
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: 607167088920.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-ecs
  newTag: 7187c17002b445b8b78d4c1dbebeb76ccce7c1da
