apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    dreamkast.cloudnativedays.jp/app-commit-hash: 974b9d08a8fdba3173ad94409691ec24a70643a2
    dreamkast.cloudnativedays.jp/app-organization: cloudnativedaysjp
    dreamkast.cloudnativedays.jp/app-repository: dreamkast
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: dreamkast-development-dk-1111
  namespace: argocd
spec:
  destination:
    namespace: dreamkast-dk-1111
    server: https://kubernetes.default.svc
  project: app
  source:
    path: manifests/app/dreamkast/overlays/development/dk-1111
    repoURL: https://github.com/cloudnativedaysjp/dreamkast-infra
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
