apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    dreamkast.cloudnativedays.jp/app-commit-hash: 9b68c9f49eadab6908ad1efeb6c8c4917d61e711
    dreamkast.cloudnativedays.jp/app-organization: cloudnativedaysjp
    dreamkast.cloudnativedays.jp/app-repository: dreamkast-ui
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: dreamkast-development-ui-200
  namespace: argocd
spec:
  destination:
    namespace: dreamkast-ui-200
    server: https://kubernetes.default.svc
  project: app
  source:
    path: manifests/app/dreamkast/overlays/development/ui-200
    repoURL: https://github.com/cloudnativedaysjp/dreamkast-infra
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
