apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    dreamkast.cloudnativedays.jp/app-commit-hash: 3cae024de1459657e244c7b4361b3ea9e4b14bb8
    dreamkast.cloudnativedays.jp/app-organization: cloudnativedaysjp
    dreamkast.cloudnativedays.jp/app-repository: dreamkast
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: dreamkast-development-dk-1070
  namespace: argocd
spec:
  destination:
    namespace: dreamkast-dk-1070
    server: https://kubernetes.default.svc
  project: app
  source:
    path: manifests/app/dreamkast/overlays/development/dk-1070
    repoURL: https://github.com/cloudnativedaysjp/dreamkast-infra
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
