#cloud-config
fqdn: ${hostname} 
chpasswd:
    list: |
      ubuntu:${vm_password}
    expire: false
users:
  - default 
  - name: ubuntu
    gecos: Local
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
    - gh:jacopen
    - gh:TakumaNakagame
    - gh:capsmalt
    - gh:Gaku-Kunimi
    - gh:ryojsb
system_info: 
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
ssh_pwauth: yes
random_seed:
    file: /dev/urandom
    command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
    command_required: true
package_upgrade: true
packages:
  - curl
  - vim
  - git
  - unzip
  - gnupg
  - lsb-release
  - ca-certificates
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
