apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.52.1/bundle.yaml
- ../../base
patchesStrategicMerge:
- prometheus.yaml
- service-selector.yaml
