---
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:

processors:
  attributes:
    actions:
      - action: upsert
        key: service.namespace
        value: dreamkast
      - action: upsert
        key: service.name
        value: dreamkast
      - action: upsert
        key: deployment.environment.name
        value: prod
  resourcedetection:
    detectors: [env, ecs]
    timeout: 2s
    override: false
  tail_sampling:
    policies:
      - name: include http 5xx response status
        type: numeric_attribute
        numeric_attribute:
          key: http.response.status_code
          min_value: 500
          max_value: 599
      - name: include http 5xx status
        type: numeric_attribute
        numeric_attribute:
          key: http.status_code  # dreamkastはこの古い仕様で送っている
          min_value: 500
          max_value: 599
      - name: include slow http
        type: latency
        latency:
          threshold_ms: 6000
      - name: include random sample
        type: probabilistic
        probabilistic:
          sampling_percentage: 0.1

exporters:
  mackerelotlp:

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [attributes, resourcedetection]
      exporters: [mackerelotlp]
    traces:
      receivers: [otlp]
      processors: [attributes, resourcedetection, tail_sampling]
      exporters: [mackerelotlp]
  extensions: [health_check]
