---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.3.3
    helm:
      releaseName: aws-load-balancer-controller
      parameters:
      - name: clusterName
        value: dreamkast-cluster
      - name: serviceAccount.create
        value: "false"
      - name: serviceAccount.name
        value: aws-load-balancer-controller
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
