---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: kubernetes-external-secrets
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    targetRevision: 8.3.0
    helm:
      releaseName: kubernetes-external-secrets
      parameters:
      - name: env.AWS_REGION
        value: ap-northeast-1
      - name: env.POLLER_INTERVAL_MILLISECONDS # This parameter defines the frequency of API calls to AWS Secrets Manager. Modify this if necessary.
        value: "120000" # By default this was 10000 but it was too expensive
      - name: env.WATCH_TIMEOUT # This parameter defines timeout value to restart control loop not to hang up in Node.js environment ref. https://github.com/external-secrets/kubernetes-external-secrets/issues/362
        value: "150000"
      - name: securityContext.fsGroup
        value: "65534"
      - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: "arn:aws:iam::607167088920:role/eksctl-dreamkast-cluster-AWSClusterExternalSecret-1WW6QED0YWDS8"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
